from django.conf.urls import url
from index import views

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^api/$", views.api, name="api"),
    url(r"^api/json/$", views.api),
    url(r"^api/xml/$", views.api),
    url(r"^dopebar/$", views.dopebar, name="dopebar"),
    url(r"^charts/$", views.charts, name="charts"),
    url(r"^previous/$", views.previous, name="previous"),
    url(r"^search/$", views.search, name="search"),
    url(r"^subscriptions/$", views.subscriptions, name="subscriptions"),
    url(r"^showpod/(?P<podid>\d+)/$", views.showpod, name="showpod"),
    url(r"^episodes/(?P<podid>\d+)/$", views.episodes, name="episodes"),
    url(r"^settings/$", views.settings, name="settings"),
    url(r"^playlist/$", views.playlist, name="playlist"),
    url(r"^privacy/$", views.privacy, name="privacy"),
    url(r"^terms/$", views.terms, name="terms"),
    url(r"^contact/$", views.contact, name="contact"),
    url(r"^login/$", views.login, name="login"),
    url(r"^signup/$", views.signup, name="signup"),
    url(r"^logout/$", views.logout, name="logout"),
    url(r"^change-password/$", views.change_password, name="change_password"),
    url(r"^password-reset/$", views.password_reset, name="password_reset"),
    url(r"^account/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$", views.password_reset_from_key, name="password_reset_from_key"),
    url(r"^account/confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email, name="confirm_email"),
    url(r"^noshow/$", views.noshow, name="noshow"),
    url(r"^tz/$", views.tz, name="tz"),
    url(r"^solong/$", views.solong, name="solong"),
    url(r"^temp/$", views.temp, name="temp"),
]
