from django.urls import include, path, re_path  # For django versions from 2.0 and up
from index import views

urlpatterns = [
    path("", views.index, name="index"),
    path("api/", views.api, name="api"),
    path("api/json/", views.api),
    path("api/xml/", views.api),
    path("dopebar/", views.dopebar, name="dopebar"),
    path("charts/", views.charts, name="charts"),
    path("previous/", views.previous, name="previous"),
    path("search/", views.search, name="search"),
    path("subscriptions/", views.subscriptions, name="subscriptions"),
    path("showpod/<int:podid>/", views.showpod, name="showpod"),
    path("episodes/<int:podid>/", views.episodes, name="episodes"),
    path("settings/", views.settings, name="settings"),
    path("playlist/", views.playlist, name="playlist"),
    path("privacy/", views.privacy, name="privacy"),
    path("terms/", views.terms, name="terms"),
    path("contact/", views.contact, name="contact"),
    path("login/", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout, name="logout"),
    path("change-password/", views.change_password, name="change_password"),
    path("password-reset/", views.password_reset, name="password_reset"),
    re_path("account/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/", views.password_reset_from_key, name="password_reset_from_key"),
    re_path("account/confirm-email/(?P<key>[-:\w]+)/", views.confirm_email, name="confirm_email"),
    path("noshow/", views.noshow, name="noshow"),
    path("tz/", views.tz, name="tz"),
    path("solong/", views.solong, name="solong"),
    path("tryout/", views.tryout, name="tryout"),
]
