# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('n_podcasts', models.IntegerField()),
                ('supa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcasts.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('n_podcasts', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('itunesid', models.IntegerField(primary_key=True, serialize=False)),
                ('feedUrl', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('explicit', models.BooleanField()),
                ('copyrighttext', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reviewsUrl', models.URLField(max_length=255)),
                ('artworkUrl', models.URLField(max_length=255)),
                ('podcastUrl', models.URLField(max_length=255)),
                ('n_subscribers', models.IntegerField()),
                ('subscribed', models.BooleanField(default=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Genre')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcasts.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedUrl', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('explicit', models.BooleanField()),
                ('copyrighttext', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reviewsUrl', models.URLField(max_length=255)),
                ('artworkUrl', models.URLField(max_length=255)),
                ('podcastUrl', models.URLField(max_length=255)),
                ('itunesid', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Genre')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcasts.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
