# Generated by Django 2.0 on 2017-12-16 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubDate', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('length', models.DurationField(blank=True, null=True)),
                ('url', models.CharField(max_length=500)),
                ('kind', models.CharField(max_length=16)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('podcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='podcasts.Podcast')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_episodes', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('podcasts.podcast',),
        ),
        migrations.RemoveField(
            model_name='podcastsubscription',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='podcastsubscription',
            name='language',
        ),
        migrations.RemoveField(
            model_name='podcastsubscription',
            name='user',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='supa',
            new_name='supergenre',
        ),
        migrations.AddField(
            model_name='genre',
            name='itunesid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='artist',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='genre_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='global_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='n_podcasts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='n_podcasts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='artworkUrl',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='copyrighttext',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='feedUrl',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='podcasts.Language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='n_subscribers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='podcastUrl',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='reviewsUrl',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='PodcastSubscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='podcasts.Podcast'),
        ),
        migrations.AddField(
            model_name='episode',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast'),
        ),
    ]
