# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='supa',
            new_name='supergenre',
        ),
    ]
