# Generated by Django 2.0 on 2018-01-29 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_auto_20180129_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
