# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 21:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0002_auto_20171104_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itunesid', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='podcastsubscription',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='podcastsubscription',
            name='language',
        ),
        migrations.RemoveField(
            model_name='podcastsubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='PodcastSubscription',
        ),
    ]
