# Generated by Django 2.0 on 2017-12-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_auto_20171216_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
