# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20171104_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='itunesid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='itunesid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
