# Generated by Django 2.0 on 2017-12-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_auto_20171220_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='subscribed',
            new_name='is_subscribed',
        ),
    ]
