# Generated by Django 2.0 on 2017-12-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_auto_20171220_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
