# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_remove_language_itunesid'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='artist',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='podcasts.Language'),
            preserve_default=False,
        ),
    ]
