# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_auto_20171127_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='itunesid',
        ),
        migrations.AddField(
            model_name='subscription',
            name='podcast_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='podcasts.Podcast'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='podcasts.Podcast'),
        ),
    ]
