# Generated by Django 2.0 on 2017-12-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_auto_20171220_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='discriminate',
            field=models.BooleanField(default=False),
        ),
    ]
