# Generated by Django 2.0 on 2017-12-29 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_podcast_discriminate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Top 50 podcasts on iTunes', max_length=30)),
                ('genre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcasts.Genre')),
                ('podcasts', models.ManyToManyField(to='podcasts.Podcast')),
            ],
        ),
    ]
