# Generated by Django 2.0 on 2018-02-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_auto_20180203_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='summary',
            new_name='description',
        ),
    ]
