# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0008_auto_20171128_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pod',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='podcasts.Podcast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
