# Generated by Django 2.0 on 2017-12-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_chart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('parent__title',)},
        ),
    ]
