# Generated by Django 2.0 on 2018-02-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_auto_20180205_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='signature',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
