# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_auto_20171128_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Genre')),
                ('pods', models.ManyToManyField(to='podcasts.Podcast')),
            ],
        ),
    ]
