# Generated by Django 2.0 on 2017-12-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_auto_20171230_0424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('-n_podcasts', 'name')},
        ),
    ]
