# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='pods',
            field=models.ManyToManyField(blank=True, null=True, to='podcasts.Podcast'),
        ),
    ]
