# Generated by Django 2.0 on 2018-02-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_episode_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
