# Generated by Django 2.0 on 2018-02-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_auto_20180205_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='signature',
            field=models.CharField(max_length=5000),
        ),
    ]
