# Generated by Django 2.0 on 2018-01-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_podcast_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('-n_podcasts',)},
        ),
    ]
