# Generated by Django 2.0 on 2018-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_auto_20180205_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='bump',
            field=models.BooleanField(default=False),
        ),
    ]
