# Generated by Django 2.0 on 2018-01-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_auto_20180104_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='itunesid',
            new_name='genreid',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='itunesid',
            new_name='podid',
        ),
    ]
