# Generated by Django 2.0.2 on 2018-02-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0013_podcast_bump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='rank',
            field=models.IntegerField(default=1000000),
        ),
    ]
