# Generated by Django 2.0 on 2018-01-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0013_auto_20180113_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='is_subscribed',
        ),
    ]
