# Generated by Django 2.0 on 2018-02-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0014_auto_20180210_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
