# Generated by Django 2.0 on 2018-01-20 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0014_remove_podcast_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='is_new',
        ),
        migrations.AddField(
            model_name='episode',
            name='played',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
