# Generated by Django 2.0.2 on 2018-02-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0015_auto_20180214_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='last_played',
            options={'ordering': ('-played',)},
        ),
        migrations.AddField(
            model_name='last_played',
            name='played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
