# Generated by Django 2.0 on 2018-02-16 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0015_auto_20180216_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Played_Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubDate', models.DateTimeField()),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('length', models.DurationField(blank=True, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('kind', models.CharField(max_length=16)),
                ('size', models.CharField(blank=True, max_length=16, null=True)),
                ('signature', models.CharField(max_length=5000)),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast')),
            ],
            options={
                'ordering': ('-played_at',),
            },
        ),
        migrations.RemoveField(
            model_name='episode',
            name='podcast',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
