# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0015_auto_20171129_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='chart',
        ),
        migrations.AddField(
            model_name='podcast',
            name='genre_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='global_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
