# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0016_auto_20171130_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='pod',
            new_name='parent',
        ),
    ]
