# Generated by Django 2.0 on 2018-02-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0016_auto_20180214_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
