# Generated by Django 2.0 on 2018-02-16 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0016_auto_20180216_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist_Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubDate', models.DateTimeField()),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('length', models.DurationField(blank=True, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('kind', models.CharField(max_length=16)),
                ('size', models.CharField(blank=True, max_length=16, null=True)),
                ('signature', models.CharField(max_length=5000)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_episode', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='played_episode',
            name='played_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='played_episode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_episode', to='podcasts.Podcast'),
        ),
    ]
