# Generated by Django 2.0.2 on 2018-02-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0017_auto_20180216_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist_episode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_episode', to='podcasts.Podcast'),
        ),
    ]
