# Generated by Django 2.0.2 on 2018-02-22 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0018_auto_20180218_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='played_episode',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='played_episode', to=settings.AUTH_USER_MODEL),
        ),
    ]
