# Generated by Django 2.0 on 2017-12-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0019_auto_20171130_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubDate', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('length', models.DurationField(blank=True, null=True)),
                ('url', models.CharField(max_length=500)),
                ('kind', models.CharField(max_length=16)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='podcast',
            name='artworkUrl',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='feedUrl',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='podcastUrl',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='reviewsUrl',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='episode',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast'),
        ),
    ]
