# Generated by Django 2.0.2 on 2018-02-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0019_played_episode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='podcasts.Language'),
        ),
    ]
