# Generated by Django 2.0.2 on 2018-02-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0020_chart_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='header',
        ),
    ]
