# Generated by Django 2.0.2 on 2018-02-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0021_remove_chart_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='language',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='podcasts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='podcast',
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
