# Generated by Django 2.0.2 on 2018-03-01 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0023_auto_20180225_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubDate', models.DateTimeField()),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('length', models.DurationField(blank=True, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('kind', models.CharField(max_length=16)),
                ('size', models.CharField(blank=True, max_length=16, null=True)),
                ('signature', models.CharField(max_length=5000)),
                ('played_at', models.DateTimeField(default=None)),
                ('added_at', models.DateTimeField(default=None)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='podcasts.Podcast')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='played_episode',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='played_episode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlist_episode',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='playlist_episode',
            name='user',
        ),
        migrations.DeleteModel(
            name='Played_Episode',
        ),
        migrations.DeleteModel(
            name='Playlist_Episode',
        ),
    ]
