# Generated by Django 2.0.2 on 2018-03-02 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0024_auto_20180302_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
