# Generated by Django 2.0.2 on 2018-03-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0025_auto_20180302_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='played_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
