# Generated by Django 2.0 on 2018-03-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0028_auto_20180305_2145'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='podcast',
            name='podcasts_po_title_b6422d_idx',
        ),
        migrations.RemoveIndex(
            model_name='podcast',
            name='podcasts_po_artist_010d17_idx',
        ),
        migrations.RemoveIndex(
            model_name='podcast',
            name='podcasts_po_genre_i_653dbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='podcast',
            name='podcasts_po_languag_73c689_idx',
        ),
        migrations.RemoveIndex(
            model_name='podcast',
            name='podcasts_po_rank_d437a5_idx',
        ),
    ]
