# Generated by Django 2.0.3 on 2018-03-21 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0030_auto_20180308_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='signature',
            field=models.CharField(max_length=7000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode', to=settings.AUTH_USER_MODEL),
        ),
    ]
