# Generated by Django 2.0.3 on 2018-03-23 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0031_auto_20180321_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='podcasts.Genre'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='podcasts.Language'),
        ),
    ]
