# Generated by Django 2.0.3 on 2018-04-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0033_auto_20180329_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='pubDate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
