# Generated by Django 2.0.4 on 2018-04-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0034_auto_20180409_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='noshow',
            field=models.BooleanField(default=False),
        ),
    ]
