# Generated by Django 2.0.4 on 2018-05-02 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0035_podcast_noshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='signature',
            field=models.CharField(max_length=10000),
        ),
    ]
