# Generated by Django 2.0.3 on 2018-03-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_profile_joined_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_explicit',
        ),
    ]
