# Generated by Django 2.0.4 on 2018-04-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_profile_show_explicit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dark_theme',
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='light', max_length=30),
        ),
    ]
