# Generated by Django 2.0.4 on 2018-05-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180420_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('christmas', 'Christmas')], default='light', max_length=10),
        ),
    ]
