# Generated by Django 2.1 on 2018-08-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180813_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined_at',
        ),
    ]
